In [3]:
#Чтобы установить numpy и matplotlib используете pip:

#pip install numpy

In [4]:
import numpy as np   # Импортируем numpy
# import matplotlib.pyplot as plt

In [5]:
# Читаем данные из файла и копим их в списках Python
X = []
Y = []
with open('../../../train_simple_reg.csv','r') as f:
    print(f.readline())
    for line in f:
        data = line.split(',')
        
        _id = int(data[0])
        y = float(data[-1])
        x = [float(_x) for _x in data[1:-1]]

        X.append(x)
        Y.append(y)

id,f1,f2,f3,f4,f5,y



In [6]:
X[:2]  # Получаем первые 2 элемента

[[0.18070408808882843,
  1.5647281060905347,
  -0.7094261503649989,
  0.2264376541882878,
  0.9813525956535327],
 [0.711181913030938,
  1.2371262336838516,
  -0.6558950580131298,
  1.0605343341336133,
  -0.3239311921771363]]

In [54]:
Y[:2]

[74.38012788587227, 14.984444617326321]

In [7]:
# Превращаем списки Python в массивы numpy
X=np.array(X)
Y=np.array(Y)

In [8]:
Y.shape # Смотрим на размеры массива

(4000,)

# Операции с массивами

In [13]:
print(X.min())# наименьший элемент по всём наборе данных

-3.887954784790062


In [16]:
print(X.min(axis=0))# наименьшие значения каждого из признаков
print(X.min(axis=0).shape)

[-3.45583396 -3.5471367  -3.75418976 -3.88795478 -3.73277268]
(5,)


In [17]:
print(X.min(axis=1))# наименьшее значение признакая для каждого объекта
print(X.min(axis=1).shape)

[-0.70942615 -0.65589506 -1.97575988 ... -1.1156751  -0.83629802
 -1.817546  ]
(4000,)


Операции перечисленные выше можно использоваться для того, чтобы отмасштабировать значения признаков – загнать значения каждого из них в интервал от 0 до 1.

In [21]:
X = (X-X.min(axis=0))/(X.max(axis=0)-X.min(axis=0))
print(X.min(), X.max())

0.0 1.0


Взятие элементов по индексу

In [22]:
corncrete_indx = 2  # Зададимся конкретным индексом

In [23]:
obj = X[corncrete_indx]  # извлекаем из массива Х объект с индексом corncrete_indx

In [25]:
indx = np.arange(X.shape[0])  # создаём упорядоченный массив целых чисел длинны X.shape[0]
# фактически значения элементов будут равны их индексам в этом массиве
print(indx)

[   0    1    2 ... 3997 3998 3999]


In [27]:
indx!=corncrete_indx   # Мы можем выполнять операции конкретного объекта со всеми элементами массива
# Результатом будет массив с результатами такого сравнения

array([ True,  True, False, ...,  True,  True,  True])

In [30]:
# Получившийся массив мы можем использовать для индексации
# Операция выполняемая ниже позволяет получить нам только те элементы массива indx,
# значения которых не равны corncrete_indx
distance_indx = indx[indx!=corncrete_indx]

In [31]:
distance_indx

array([   0,    1,    3, ..., 3997, 3998, 3999])

In [32]:
# Вычисленияе расстояния по Эвклидовой метрике

In [33]:
_X = X[indx!=corncrete_indx] # Уберём из массива X все элементы кроме того до которого мы будем вычислять расстояния

In [35]:
_X-obj

array([[-0.23065422,  0.40457702, -0.29835268,  0.15492239,  0.39742053],
       [-0.16043829,  0.3591541 , -0.29079281,  0.2638906 ,  0.22199718],
       [-0.16502548, -0.05736679, -0.31402804, -0.05376534,  0.35398219],
       ...,
       [-0.13363632,  0.03293162, -0.21745005,  0.14326038,  0.26606857],
       [-0.36526824,  0.39097564, -0.15920263,  0.16672692,  0.38737659],
       [-0.49514972, -0.02338304,  0.07926406,  0.13504464,  0.37531431]])

In [34]:
(_X-obj)**2  # Квадраты разностей значений признаков

array([[0.05320137, 0.16368256, 0.08901432, 0.02400095, 0.15794308],
       [0.02574045, 0.12899167, 0.08456046, 0.06963825, 0.04928275],
       [0.02723341, 0.00329095, 0.09861361, 0.00289071, 0.12530339],
       ...,
       [0.01785866, 0.00108449, 0.04728452, 0.02052354, 0.07079248],
       [0.13342089, 0.15286195, 0.02534548, 0.02779787, 0.15006062],
       [0.24517324, 0.00054677, 0.00628279, 0.01823705, 0.14086083]])

In [38]:
distance_to_obj = np.sum(
    (_X-obj)**2, axis=1
)  # Сумма квадратов разностей значений признаков
print(distance_to_obj)

[0.48784229 0.35821357 0.25733207 ... 0.1575437  0.48948681 0.41110068]


In [39]:
distance_to_obj.argsort()  # индексы объектов отсортированных по возрастанию расстояния до конкретного объекта

array([2671, 3620,  942, ..., 1199, 1849, 3953])

In [40]:
distance_to_obj[distance_to_obj.argsort()]  # значения расстояний до ближайших объектов

array([0.02290013, 0.02621452, 0.02764235, ..., 0.91734814, 0.95654404,
       1.00650154])

In [42]:
X[indx[distance_to_obj.argsort()]]  # Значения признаков ближайших объектов

array([[0.43932157, 0.41115207, 0.78295698, 0.65294875, 0.21194237],
       [0.44879876, 0.66311588, 0.59412921, 0.59148398, 0.40078099],
       [0.35718662, 0.55311207, 0.53348566, 0.45749149, 0.20946876],
       ...,
       [0.59240077, 0.51385702, 0.56340702, 0.53214213, 0.30533416],
       [0.47462647, 0.36257036, 0.37909649, 0.5841064 , 0.47721764],
       [0.44724866, 0.32653142, 0.41383422, 0.58876629, 0.50883307]])

In [43]:
Y[indx[distance_to_obj.argsort()]]  # Значения целевой переменной ближайших объектов

array([ -81.99921871,  -19.6009384 , -187.51779037, ..., -100.38786266,
         -4.87821962,   19.44832853])

In [44]:
Y[indx[distance_to_obj.argsort()]][:10]  # Значения целевой переменной 10 ближайших объектов

array([ -81.99921871,  -19.6009384 , -187.51779037,  -84.2587302 ,
          4.78287164,   84.98812167,   28.97053757,   44.87845996,
         44.39630113,  -71.16287445])

In [45]:
Y[corncrete_indx]  # Значение целевой переменной объекта, до которого мы мерели расстояния

-175.1298811690295

### ???????????

### PROFIT

# Перемножение матриц

In [60]:
W = np.array([5.4, 7.5, 4.1, 32, 36])  

In [61]:
X.dot(W) # перемножаем исходную матрицу признаков X с "каким-то" весами этих признаов W

array([49.68640974, 46.92764167, 29.85620533, ..., 42.65281193,
       49.44416211, 45.16475021])

In [67]:
X.dot(W)-Y  # Считаем разницу с истинным значением

array([-24.69371815,  31.94319706, 204.9860865 , ...,  37.95343447,
       -40.85588127, -56.69045748])

In [68]:
(X.dot(W)-Y)**2  # Считаем квадрат ошибки

array([  609.77971609,  1020.36783815, 42019.29565822, ...,
        1440.46318844,  1669.20303412,  3213.80796882])

In [69]:
((X.dot(W)-Y)**2).mean()# считаем средний квадрат ошибки по всей выборке

9627.306859745982

In [70]:
((X.dot(W)-Y)**2).mean()**0.5  # Считаем корень из среднеквадратичной ошибки

98.11884049328133

In [71]:
# Теперь можно повторять операцию подбора параметров до момента успеха

In [72]:
# Внимание, здесь все действия показывались исключительно на тренировочной выборке X,
# собранной из файлика train_simple_reg